name: BOAppTestVars

trigger:
  none

pool:
  vmImage: 'windows-2022'
  timeoutInMinutes: 60

variables:
- template: envspec.yml

stages:
  - stage: Build
    jobs:
      - job: SetSkipVariable
        steps:
          - task: PowerShell@2
            displayName: 'Set Variable to Skip Stages'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "$(currentEnv)"
                Write-Host "$(solution)"
                Write-Host "$(project)"
                if ('$(StageEnvironment)' -eq 'PLWAWS86DEV') {
                  Write-Host "Skipping further stages for DEV"
                  Write-Host "##vso[task.setvariable variable=skipStages;isOutput=true]true"
                  Write-Host "##vso[task.setvariable variable=currentEnv]nowawartosc"
                  $(PROD) = false
                } else {
                  Write-Host "Proceeding with the pipeline."
                  Write-Host "##vso[task.setvariable variable=skipStages;isOutput=true]false"
                  Write-Host "##vso[task.setvariable variable=currentEnv;isOutput=true]nowawartoscelse"
                  $(PROD) = true
                }

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    # condition: eq(dependencies.Build.outputs['Build.SetSkipVariable.currentEnv'], 'nowawartoscelse')
    jobs:
      - job: DeployJob
        steps:
          - task: PowerShell@2
            displayName: 'Deploy to Production'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Deploying to production."
                Write-Host $[stageDependencies.Build.outputs['Build.SetSkipVariable.currentEnv']
                Write-Host "Deploying to production with variable PROD = $(PROD)."
