#DEV RELEASE Pipeline

trigger:
  none

variables:
  IISWebsiteName: 'BackOfficeApp'

resources:
  pipelines:
    - pipeline: 'buildPipeline'
      project: 'BackOfficeApp'
      source: 'BOApp Build Pipeline'
      branch: 'master'