stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
    - powershell: |
        Write-Host "This is Stage 1"
        Write-Host "##vso[task.setvariable variable=Stage1Completed;isOutput=true]true"

- stage: Stage2
  dependsOn: Stage1
  condition: and(succeededOrFailed(), eq(dependencies.Stage1.outputs['Job1.Stage1Completed'], 'true'))
  jobs:
  - job: Job2
    steps:
    - powershell: |
        Write-Host "This is Stage 2"
        Write-Host "##vso[task.setvariable variable=Stage2Completed;isOutput=true]true"

- stage: Stage3
  dependsOn: Stage2
  condition: always()
  jobs:
  - job: Job3
    steps:
    - powershell: |
        if ($env:Stage1Completed -eq "true") {
          Write-Host "Stage 1 was completed"
        } else {
          Write-Host "Stage 1 was skipped"
        }
        if ($env:Stage2Completed -eq "true") {
          Write-Host "Stage 2 was completed"
        } else {
          Write-Host "Stage 2 was skipped"
      env:
        Stage1Completed: $[ dependencies.Stage1.outputs['Job1.Stage1Completed'] ]
        Stage2Completed: $[ dependencies.Stage2.outputs['Job2.Stage2Completed'] ]
