#DEV RELEASE Pipeline

trigger:
  none

variables:
  IISWebsiteName: 'BackOfficeApp'

resources:
  pipelines:
    - pipeline: 'buildPipeline'
      project: 'BackOfficeApp'
      source: 'BOApp Build Pipeline'
      branch: 'master'

stages:
  - stage: DeployToDEV
    displayName: 'Deploy to DEV'
    jobs:
      - deployment: DeployWebApp
        displayName: 'Deploy Web App to DEV'
        environment: 'PLWAWS86DEV.PLWAWS86DEV'
        pool:
          vmImage: 'windows-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - download: 'buildPipeline'
                  name: 'DownloadArtifacts'
                  displayName: 'Download Artifacts'
                  artifact: 'BoAppTestProject'

                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StopIIS'
                  displayName: 'Stop IIS'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StopWebsite'
                    StartStopWebsiteName: '$(IISWebsiteName)'

                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: 'DeployApp'
                  displayName: 'Deploy App'
                  inputs:
                    WebSiteName: '$(IISWebsiteName)'
                    Package: '$(Pipeline.Workspace)/buildPipeline/BoAppTestProject/BOAppFluentUI'
                    TakeAppOfflineFlag: true

                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartApp'
                  displayName: 'Start App'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: '$(IISWebsiteName)'
