// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

#nullable disable

namespace Persistance.Migrations.AsDb
{
    [DbContext(typeof(AsDbContext))]
    [Migration("20240908221940_RenameKontrahenciTo_v_KONTRAHENCI_LISTA")]
    partial class RenameKontrahenciTo_v_KONTRAHENCI_LISTA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Accounting.Customer", b =>
                {
                    b.Property<long>("KontrahentId")
                        .HasColumnType("bigint")
                        .HasColumnName("KONTRAHENT_ID");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)")
                        .HasColumnName("NAZWA")
                        .UseCollation("Polish_CI_AS");

                    b.Property<string>("Nip")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NIP")
                        .UseCollation("Polish_CI_AS");

                    b.Property<bool>("Przelew")
                        .HasColumnType("bit")
                        .HasColumnName("PRZELEW");

                    b.ToTable("v_KONTRAHENCI_LISTA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
