// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

#nullable disable

namespace Persistance.Migrations.AsDb
{
    [DbContext(typeof(AsDbContext))]
    partial class AsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Accounting.Customer", b =>
                {
                    b.Property<int>("CC")
                        .HasColumnType("int");

                    b.Property<long>("Faktdoc_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("KontrahentId")
                        .HasColumnType("bigint")
                        .HasColumnName("KONTRAHENT_ID");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)")
                        .HasColumnName("NAZWA")
                        .UseCollation("Polish_CI_AS");

                    b.Property<string>("Nip")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NIP")
                        .UseCollation("Polish_CI_AS");

                    b.Property<string>("Numer_Fk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Przelew")
                        .HasColumnType("bit")
                        .HasColumnName("PRZELEW");

                    b.Property<bool>("is_Firma")
                        .HasColumnType("bit");

                    b.ToTable("v_KONTRAHENCI_LISTA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
